"use client";

import { useEffect, useMemo, useState } from "react";
import { AppState, Lifeguard, RequestItem, Shift, ShiftType, addDaysIso, blankState, csvSafe, longDate, niceDate, openCount, todayIso } from "../lib/schedule";

type View = "entry" | "select" | "confirm" | "adminPin" | "admin";
type ReportRow = { dateIso: string; date: string; am: string; pm: string; open: number };

const ADMIN_CODE = "7900";
const STORAGE_KEY = "serenity-shores-lifeguard-scheduler-v5";
const SCHEDULE_LIMIT_DAYS = 14;
const PIN_DIGITS = 6;

function normalizeState(input: AppState): AppState { return { ...blankState(), ...input, lifeguards: Array.isArray(input.lifeguards) ? input.lifeguards : [], requests: Array.isArray(input.requests) ? input.requests : [], shifts: Array.isArray(input.shifts) ? input.shifts : blankState().shifts }; }
function startOfWeekIso(offsetDays = 0) { const d = new Date(); d.setHours(12,0,0,0); d.setDate(d.getDate()+offsetDays); d.setDate(d.getDate()-d.getDay()); return d.toISOString().slice(0,10); }
function endFromStart(start: string, days: number) { const d = new Date(`${start}T12:00:00`); d.setDate(d.getDate()+days); return d.toISOString().slice(0,10); }
function sameName(a: string, b: string) { return a.trim().toLowerCase() === b.trim().toLowerCase(); }
function cleanPin(value: string) { return value.replace(/\D/g, "").slice(0, PIN_DIGITS); }
function colorForName(name: string) { let hash = 0; for (let i = 0; i < name.length; i++) hash = (hash * 31 + name.charCodeAt(i)) % 360; return `hsl(${hash} 82% 88%)`; }
function borderForName(name: string) { let hash = 0; for (let i = 0; i < name.length; i++) hash = (hash * 31 + name.charCodeAt(i)) % 360; return `hsl(${hash} 62% 42%)`; }
function guardList(shift?: Shift) { const names = shift?.assignments.map((a) => a.name.trim()).filter(Boolean) || []; return names.length ? names.join(", ") : "OPEN"; }
function overCount(shift: Shift) { return Math.max(0, shift.assignments.length - shift.required); }
function shiftText(shift?: Shift) { if (!shift) return "OPEN - 3 needed"; const needed = openCount(shift); const over = overCount(shift); return `${guardList(shift)}${over > 0 ? ` - ${over} over` : needed > 0 ? ` - ${needed} needed` : " - Full"}`; }
function rowsBetween(shifts: Shift[], start: string, end: string): ReportRow[] { const byDate = new Map<string, ReportRow>(); shifts.filter((s)=>s.date>=start&&s.date<=end).forEach((s)=>{ const row = byDate.get(s.date) || { dateIso:s.date, date:longDate(s.date), am:"", pm:"", open:0 }; if(s.type==="AM") row.am=shiftText(s); else row.pm=shiftText(s); row.open += openCount(s); byDate.set(s.date,row); }); return Array.from(byDate.values()).sort((a,b)=>a.dateIso.localeCompare(b.dateIso)); }

export default function Home() {
  const [state, setState] = useState<AppState>(() => blankState());
  const [shared, setShared] = useState(false);
  const [syncStatus, setSyncStatus] = useState("Loading schedule...");
  const [view, setView] = useState<View>("entry");
  const [name, setName] = useState("");
  const [lifeguardPin, setLifeguardPin] = useState("");
  const [loginError, setLoginError] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [pin, setPin] = useState("");
  const [adminAuthed, setAdminAuthed] = useState(false);
  const [reportStart, setReportStart] = useState(() => todayIso());
  const [reportEnd, setReportEnd] = useState(() => addDaysIso(14));
  const [manualName, setManualName] = useState("");
  const [edit, setEdit] = useState<{ shiftId: string; oldName: string; value: string } | null>(null);
  const [resetText, setResetText] = useState("");
  const [scheduleWindow, setScheduleWindow] = useState<"current" | "next">("current");
  const [guardForm, setGuardForm] = useState<{ id: string; name: string; pin: string }>({ id: "", name: "", pin: "" });

  async function loadShared() { try { const res = await fetch("/api/state", { cache: "no-store" }); if (!res.ok) throw new Error("state"); const data = await res.json(); const next = normalizeState(data.state as AppState); setState(next); setShared(Boolean(data.shared)); setSyncStatus(data.shared ? "Shared database connected" : "Testing mode: browser storage only"); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); } catch { const saved = localStorage.getItem(STORAGE_KEY); if (saved) setState(normalizeState(JSON.parse(saved) as AppState)); setSyncStatus("Offline fallback: browser storage only"); } }
  async function persist(nextInput: AppState, replace = false, hardReplace = false) { const next = normalizeState({ ...nextInput, updatedAt: new Date().toISOString() }); setState(next); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); try { const res = await fetch("/api/state", { method:"PUT", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ state: next, replace, hardReplace }) }); const data = await res.json(); if (data.ok) { const saved = normalizeState(data.state as AppState); setState(saved); setShared(Boolean(data.shared)); setSyncStatus(data.shared ? "Shared database connected" : "Testing mode: browser storage only"); } } catch { setSyncStatus("Offline fallback: browser storage only"); } }
  useEffect(() => { void loadShared(); }, []);
  function updateState(updater: (current: AppState) => AppState, replace = false) { void persist(updater(state), replace); }

  const selectedName = name.trim();
  const selectableEnd = addDaysIso(SCHEDULE_LIMIT_DAYS);
  const twoWeekDates = useMemo(() => Array.from(new Set(state.shifts.filter((s)=>s.date>=todayIso()&&s.date<=selectableEnd).map((s)=>s.date))).sort(), [state.shifts, selectableEnd]);
  const myRequests = useMemo(() => state.requests.filter((r)=>sameName(r.name, selectedName)), [state.requests, selectedName]);
  const pendingRequests = state.requests.filter((r)=>r.status==="pending");
  const reportRows = rowsBetween(state.shifts, reportStart, reportEnd);
  const currentStart = startOfWeekIso(scheduleWindow === "current" ? 0 : 7);
  const currentEnd = endFromStart(currentStart, 6);
  const adminRows = rowsBetween(state.shifts, currentStart, currentEnd);
  const weekCounts = useMemo(() => { const m = new Map<string, number>(); state.shifts.filter((s)=>s.date>=currentStart&&s.date<=currentEnd).forEach((s)=>s.assignments.forEach((a)=>m.set(a.name, (m.get(a.name)||0)+1))); return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])); }, [state.shifts,currentStart,currentEnd]);
  const requestCounts = useMemo(() => { const m = new Map<string, number>(); state.requests.forEach((r)=>m.set(r.name, (m.get(r.name)||0)+1)); return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])); }, [state.requests]);

  function findShift(date: string, type: ShiftType) { return state.shifts.find((s)=>s.date===date && s.type===type); }
  function alreadyAssigned(shift: Shift, guardName: string) { return shift.assignments.some((a)=>sameName(a.name, guardName)); }
  function submitName() { const cleanName = selectedName; const cleanGuardPin = cleanPin(lifeguardPin); const match = state.lifeguards.find((g)=>sameName(g.name, cleanName) && g.pin===cleanGuardPin); if(!cleanName || cleanGuardPin.length!==PIN_DIGITS) { setLoginError("Enter your first name and six digit PIN."); return; } if(!match) { setLoginError("That name and PIN do not match an active lifeguard record. Ask Hollie/admin to add or correct your PIN."); return; } setName(match.name); setLoginError(""); setView("select"); }
  function toggleShift(shiftId: string) { const shift = state.shifts.find((s)=>s.id===shiftId); if(!shift || shift.date<todayIso() || shift.date>selectableEnd) return; setSelected((cur)=>cur.includes(shiftId)?cur.filter((id)=>id!==shiftId):[...cur, shiftId]); }
  function submitRequests() { if(!selectedName || !selected.length) return; const existing = new Set(state.requests.filter((r)=>sameName(r.name, selectedName) && r.status!=="rejected").map((r)=>r.shiftId)); const now = new Date().toISOString(); const newRequests = selected.filter((shiftId)=>!existing.has(shiftId)).map((shiftId)=>({ id:`${shiftId}-${selectedName}-${Date.now()}-${Math.random().toString(16).slice(2)}`, shiftId, name:selectedName, status:"pending" as const, createdAt:now })); if(newRequests.length) updateState((cur)=>({...cur, requests:[...cur.requests, ...newRequests]})); setSelected([]); setView("confirm"); }
  function approveRequest(request: RequestItem) { updateState((cur)=>{ const shift = cur.shifts.find((s)=>s.id===request.shiftId); if(!shift) return { ...cur, requests: cur.requests.map((r)=>r.id===request.id ? {...r,status:"approved" as const} : r) }; const nextShifts = alreadyAssigned(shift, request.name) ? cur.shifts : cur.shifts.map((s)=>s.id===request.shiftId ? { ...s, assignments:[...s.assignments,{name:request.name, source:"request" as const}] } : s); return { ...cur, shifts: nextShifts, requests: cur.requests.map((r)=>r.id===request.id ? {...r,status:"approved" as const} : r) }; }, true); }
  function rejectRequest(request: RequestItem) { updateState((cur)=>({...cur, requests:cur.requests.map((r)=>r.id===request.id ? {...r,status:"rejected" as const} : r)}), true); }
  function approveAll() { updateState((cur)=>{ const shifts = cur.shifts.map((s)=>({...s, assignments:[...s.assignments]})); const requests = cur.requests.map((r)=>({...r})); for (const r of requests.filter((x)=>x.status==="pending")) { const idx = shifts.findIndex((s)=>s.id===r.shiftId); if (idx >= 0 && !alreadyAssigned(shifts[idx], r.name)) shifts[idx] = {...shifts[idx], assignments:[...shifts[idx].assignments,{name:r.name, source:"request" as const}]}; r.status = "approved"; } return {...cur, shifts, requests}; }, true); }
  function addManualToShift(shiftId: string, guardName: string) { const clean = guardName.trim(); if(!clean) return; updateState((cur)=>({...cur, shifts:cur.shifts.map((s)=>s.id===shiftId && !alreadyAssigned(s,clean) ? {...s, assignments:[...s.assignments,{name:clean, source:"manual" as const}]} : s), requests:cur.requests.map((r)=>r.shiftId===shiftId && sameName(r.name, clean) ? {...r,status:"approved" as const} : r)}), true); }
  function addManual(shiftId: string) { addManualToShift(shiftId, manualName); setManualName(""); }
  function removeAssignment(shiftId: string, oldName: string) { updateState((cur)=>({...cur, shifts:cur.shifts.map((s)=>s.id===shiftId ? {...s, assignments:s.assignments.filter((a)=>!sameName(a.name,oldName))} : s)}), true); }
  function saveEdit() { if(!edit || !edit.value.trim()) return; updateState((cur)=>({...cur, shifts:cur.shifts.map((s)=>s.id===edit.shiftId ? {...s, assignments:s.assignments.map((a)=>sameName(a.name,edit.oldName) ? {...a,name:edit.value.trim()} : a)} : s)}), true); setEdit(null); }
  function saveLifeguard() { const cleanName = guardForm.name.trim(); const cleanGuardPin = cleanPin(guardForm.pin); if(!cleanName || cleanGuardPin.length!==PIN_DIGITS) return; updateState((cur)=>{ const guard:Lifeguard={id:guardForm.id || `${cleanName.toLowerCase()}-${Date.now()}`, name:cleanName, pin:cleanGuardPin}; const exists=cur.lifeguards.some((g)=>g.id===guard.id); return {...cur, lifeguards: exists ? cur.lifeguards.map((g)=>g.id===guard.id?guard:g) : [...cur.lifeguards, guard]}; }, true); setGuardForm({id:"",name:"",pin:""}); }
  function deleteLifeguard(id: string) { updateState((cur)=>({...cur, lifeguards:cur.lifeguards.filter((g)=>g.id!==id)}), true); }
  function resetAll() { if(resetText!=="RESET SCHEDULE") return; void persist({...blankState(), lifeguards:state.lifeguards}, false, true); setResetText(""); }

  function potentialRequestsForShift(shift: Shift) { const seen = new Set<string>(); return state.requests.filter((r)=>r.shiftId===shift.id && !alreadyAssigned(shift,r.name)).sort((a,b)=> (a.status===b.status?b.createdAt.localeCompare(a.createdAt):a.status==="pending"?-1:1)).filter((r)=>{ const k=r.name.toLowerCase(); if(seen.has(k)) return false; seen.add(k); return true; }); }
  function renderNameChip(guardName: string, action?: "add" | "remove", onClick?: () => void, status?: string) { return <span className="guardChip" style={{ background: colorForName(guardName), borderColor: borderForName(guardName) }}><strong>{guardName}</strong>{status ? <em>{status}</em> : null}{action ? <button className={action === "add" ? "chipAction add" : "chipAction remove"} onClick={onClick} type="button" aria-label={`${action === "add" ? "Add" : "Remove"} ${guardName}`}>{action === "add" ? "+" : "−"}</button> : null}</span>; }
  function renderLifeguardShift(shift: Shift) { const requested=myRequests.some((r)=>r.shiftId===shift.id && r.status!=="rejected"); const isSelected=selected.includes(shift.id); const meAssigned=shift.assignments.some((a)=>sameName(a.name, selectedName)); const names=shift.assignments.map((a)=>a.name).filter(Boolean); const coworkers=names.filter((n)=>!sameName(n,selectedName)); return <button key={shift.id} className="shiftBtn" data-selected={isSelected} disabled={requested || meAssigned} onClick={()=>toggleShift(shift.id)}><span className="shiftTitle"><span>{shift.type==="AM"?"Morning":"Afternoon"}</span><span>{shift.start} - {shift.end}</span></span><span className="shiftMeta">Approved: {names.length?names.join(", "):"No one yet"}</span>{meAssigned?<span className="shiftMeta">You work this shift{coworkers.length?` with ${coworkers.join(", ")}`:""}.</span>:null}<span>{meAssigned?<span className="badge badgeFull">You work</span>:null} <span className={overCount(shift)>0?"badge badgeDanger":openCount(shift)>0?"badge badgeOpen":"badge badgeFull"}>{overCount(shift)>0?`${overCount(shift)} over`:openCount(shift)>0?`${openCount(shift)} open`:"Full"}</span> {requested?<span className="badge badgePending">Requested</span>:null} {isSelected?<span className="badge badgePending">Selected</span>:null}</span></button>; }
  function renderAdminCell(date:string,type:ShiftType) { const shift=findShift(date,type); if(!shift) return <span className="small">No shift</span>; const potentials=potentialRequestsForShift(shift); return <div className="adminShiftCell"><div className="cellTime">{type} · {shift.start} - {shift.end}</div><div className="nameWrap">{shift.assignments.length===0?<span className="openText">OPEN</span>:null}{shift.assignments.map((a)=>renderNameChip(a.name,"remove",()=>removeAssignment(shift.id,a.name)))}</div><span className={overCount(shift)>0?"badge badgeDanger":openCount(shift)>0?"badge badgeOpen":"badge badgeFull"}>{overCount(shift)>0?`${overCount(shift)} overfilled`:openCount(shift)>0?`${openCount(shift)} open`:"Full"}</span>{potentials.length?<div className="alternateBox"><div className="small">Available alternates</div><div className="nameWrap">{potentials.map((r)=>renderNameChip(r.name,"add",()=>approveRequest(r),r.status))}</div></div>:null}</div>; }
  function exportReport() { const rows=rowsBetween(state.shifts, reportStart, reportEnd); const csv=["Serenity Shores Pool Schedule",`${longDate(reportStart)} through ${longDate(reportEnd)}`,"","Date,AM 10-3:30,PM 3:30-10,Open Spots",...rows.map((r)=>[r.date,r.am,r.pm,String(r.open)].map(csvSafe).join(","))].join("\n"); const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download=`serenity-shores-pool-schedule-${reportStart}-to-${reportEnd}.csv`; link.click(); URL.revokeObjectURL(url); }

  return <main className="appShell"><div className="topStrip">Serenity Shores pool · Lifeguard schedule</div><header className="header"><button className="brand" onClick={()=>setView("entry")} style={{border:0,background:"transparent",cursor:"pointer"}}><div className="brandText">Lifeguard Schedule</div></button><button className="adminBtn" onClick={()=>setView(adminAuthed?"admin":"adminPin")}>Admin</button></header><section className="main"><p className="small" style={{marginTop:0}}>{syncStatus} · {shared?"shared":"local"}</p>
    {view==="entry"?<div className="card hero stack"><span className="kicker">Lifeguard check-in</span><h1>Help fill the pool schedule.</h1><p className="lead">Enter your first name and your six digit PIN, then select ALL SHIFTS YOU ARE AVAILABLE TO COVER. (You will not get all of the shifts you select, and no one will have a double shift).</p><input className="input" placeholder="First name" value={name} onChange={(e)=>setName(e.target.value)} /><input className="input" inputMode="numeric" placeholder="Six digit PIN" value={lifeguardPin} onChange={(e)=>setLifeguardPin(cleanPin(e.target.value))} onKeyDown={(e)=>e.key==="Enter"&&submitName()} />{loginError?<p className="small" style={{color:"#b42318"}}>{loginError}</p>:null}<button className="primaryBtn" onClick={submitName}>See Open Shifts</button><p className="small">Lifeguards can request shifts from today through {niceDate(selectableEnd)}. New shifts unlock automatically each day.</p></div>:null}
    {view==="select"?<div className="stack"><div className="card stack"><h2>Hi, {selectedName}</h2><p className="small">Select every AM and PM shift you are available to cover. You may select both shifts on the same day if you are available all day. Hollie will approve the final schedule.</p></div><div className="card stack"><h3>Approved schedule: next two weeks</h3>{twoWeekDates.map((date)=><div className="shiftCard" key={date}><div className="dateLine">{niceDate(date)}</div><div className="shiftGrid">{["AM","PM"].map((t)=>{const s=findShift(date,t as ShiftType); return s?renderLifeguardShift(s):null;})}</div></div>)}</div><div className="stickySubmit"><div className="stickySubmitInner"><button className="primaryBtn" disabled={!selected.length} onClick={submitRequests}>Submit {selected.length||""} shift request{selected.length===1?"":"s"}</button><span className="small">Hollie/admin must approve before names appear on the final schedule.</span></div></div></div>:null}
    {view==="confirm"?<div className="card hero stack"><span className="kicker">Submitted</span><h1>Thank you.</h1><p className="lead">Your available shifts were sent to admin for approval.</p><button className="primaryBtn" onClick={()=>setView("entry")}>Done</button></div>:null}
    {view==="adminPin"?<div className="card hero stack"><span className="kicker">Admin access</span><h1>Enter code.</h1><input className="input" inputMode="numeric" placeholder="Admin code" value={pin} onChange={(e)=>setPin(e.target.value)} /><button className="primaryBtn" onClick={()=>{if(pin===ADMIN_CODE){setAdminAuthed(true);setView("admin");}}}>Open Admin</button><button className="ghostBtn" onClick={()=>setView("entry")}>Back</button></div>:null}
    {view==="admin"?<div className="stack"><div className="card stack"><span className="kicker">Admin dashboard</span><h2>Schedule control</h2><div className="panelGrid"><div className="stat"><div className="statNum">{pendingRequests.length}</div><div className="statLabel">Pending</div></div><div className="stat"><div className="statNum">{state.lifeguards.length}</div><div className="statLabel">Lifeguards</div></div><div className="stat"><div className="statNum">{state.shifts.filter((s)=>overCount(s)>0).length}</div><div className="statLabel">Overfilled shifts</div></div></div><div className="actions"><button className="primaryBtn" onClick={approveAll}>Approve All Pending</button><button className="ghostBtn" onClick={()=>void loadShared()}>Refresh</button></div><p className="small">Approve All now approves every pending request and intentionally allows overfilled shifts. Then use the colored + and − buttons below to balance the final schedule.</p></div>
      <div className="card stack"><div className="row"><div><h3>{scheduleWindow==="current"?"Current":"Next"} week schedule</h3><p className="small">{longDate(currentStart)} through {longDate(currentEnd)}</p></div><button className="ghostBtn" onClick={()=>setScheduleWindow(scheduleWindow==="current"?"next":"current")}>{scheduleWindow==="current"?"Show next week":"Show current week"}</button></div>{adminRows.map((r)=><div className="adminDay" key={r.dateIso}><div className="dateLine">{niceDate(r.dateIso)}</div><div className="adminGrid"><div>{renderAdminCell(r.dateIso,"AM")}</div><div>{renderAdminCell(r.dateIso,"PM")}</div></div></div>)}<div className="stack"><h3>Balance helper</h3><p className="small">Each name keeps the same color throughout the schedule. Remove overfilled guards with the grey − button, then add alternates with +.</p><div className="nameWrap">{weekCounts.length?weekCounts.map(([n,c])=><span className="guardChip" style={{background:colorForName(n),borderColor:borderForName(n)}} key={n}><strong>{n}</strong><em>{c} shift{c===1?"":"s"}</em></span>):<span className="small">No approved shifts this week.</span>}</div><h3>Submitted availability counts</h3><div className="nameWrap">{requestCounts.length?requestCounts.map(([n,c])=><span className="guardChip" style={{background:colorForName(n),borderColor:borderForName(n)}} key={n}><strong>{n}</strong><em>{c} request{c===1?"":"s"}</em></span>):<span className="small">No submitted requests.</span>}</div></div></div>
      <div className="card stack"><h3>Approve or deny requests</h3><p className="small">The calendar above is the main approval tool. This list is only for individual review.</p>{pendingRequests.length===0?<p className="small">No pending requests.</p>:pendingRequests.map((r)=>{const s=state.shifts.find((x)=>x.id===r.shiftId); return <div className="requestRow" key={r.id}><div><strong>{r.name}</strong><br/><span className="small">{s?`${niceDate(s.date)} · ${s.type} · ${s.start}-${s.end}`:r.shiftId}</span></div><div className="actions"><button className="primaryBtn" onClick={()=>approveRequest(r)}>Approve</button><button className="ghostBtn" onClick={()=>rejectRequest(r)}>Deny</button></div></div>;})}</div>
      <div className="card stack"><h3>Lifeguards and PINs</h3><input className="input" placeholder="Lifeguard first name" value={guardForm.name} onChange={(e)=>setGuardForm({...guardForm,name:e.target.value})}/><input className="input" inputMode="numeric" placeholder="Six digit PIN" value={guardForm.pin} onChange={(e)=>setGuardForm({...guardForm,pin:cleanPin(e.target.value)})}/><div className="actions"><button className="primaryBtn" onClick={saveLifeguard}>{guardForm.id?"Save Lifeguard":"Add Lifeguard"}</button>{guardForm.id?<button className="ghostBtn" onClick={()=>setGuardForm({id:"",name:"",pin:""})}>Cancel</button>:null}</div><div className="nameWrap">{state.lifeguards.sort((a,b)=>a.name.localeCompare(b.name)).map((g)=><span className="guardChip" style={{background:colorForName(g.name),borderColor:borderForName(g.name)}} key={g.id}><strong>{g.name}</strong><em>{g.pin}</em><button className="miniBtn" onClick={()=>setGuardForm(g)}>Edit</button><button className="miniBtn danger" onClick={()=>deleteLifeguard(g.id)}>Delete</button></span>)}</div></div>
      <div className="card stack"><h3>Manual schedule tools</h3><input className="input" placeholder="Name to add manually" value={manualName} onChange={(e)=>setManualName(e.target.value)}/>{adminRows.map((r)=><div className="requestRow" key={`add-${r.dateIso}`}><span>{niceDate(r.dateIso)}</span><div className="actions"><button className="ghostBtn" onClick={()=>{const s=findShift(r.dateIso,"AM"); if(s) addManual(s.id);}}>Add AM</button><button className="ghostBtn" onClick={()=>{const s=findShift(r.dateIso,"PM"); if(s) addManual(s.id);}}>Add PM</button></div></div>)}</div>
      <div className="card stack"><h3>Export report</h3><div className="row"><input className="input" type="date" value={reportStart} onChange={(e)=>setReportStart(e.target.value)}/><input className="input" type="date" value={reportEnd} onChange={(e)=>setReportEnd(e.target.value)}/></div><button className="primaryBtn" onClick={exportReport}>Download CSV</button></div>
      <div className="card stack dangerZone"><h3>Reset schedule</h3><p className="small">This clears schedule and requests but keeps lifeguard names/PINs. Type RESET SCHEDULE.</p><input className="input" value={resetText} onChange={(e)=>setResetText(e.target.value)}/><button className="dangerBtn" onClick={resetAll}>Reset Everything</button></div></div>:null}
    {edit?<div className="modal"><div className="modalCard stack"><h3>Edit approved guard</h3><input className="input" value={edit.value} onChange={(e)=>setEdit({...edit,value:e.target.value})}/><div className="actions"><button className="primaryBtn" onClick={saveEdit}>Save</button><button className="ghostBtn" onClick={()=>removeAssignment(edit.shiftId, edit.oldName)}>Remove</button><button className="ghostBtn" onClick={()=>setEdit(null)}>Cancel</button></div></div></div>:null}
  </section></main>;
}